FIELD_NAMES = [
    # "type",
    "timestamp",
    # "elb",
    "client_ip",
    # "client_port",
    # "target_ip",
    # "target_port",
    # "request_processing_time",
    # "target_processing_time",
    # "response_processing_time",
    "elb_status_code",
    "target_status_code",
    # "received_bytes",
    # "sent_bytes",
    "request_verb",
    "request_url",
    # "request_proto",
    # "user_agent",
    # "ssl_cipher",
    # "ssl_protocol",
    # "target_group_arn",
    # "trace_id",
    # "domain_name",
    # "chosen_cert_arn",
    # "matched_rule_priority",
    # "request_creation_time",
    # "actions_executed",
    # "redirect_url",
    # "error_reason"
]
